---
- name: Create Tags
  include_tasks: create_tags.yml

- name: Create VM's
  include_tasks: create_vm.yml
  loop:
    - dev-rhel8-1
    - dev-rhel8-2
    - dev-rhel8-3
  tags: [never, deploy]

- name: Delete VM's
  include_tasks: create_vm.yml
  loop:
    - dev-rhel8-1
    - dev-rhel8-2
    - dev-rhel8-3
  tags: [never, delete]

- name: Create snapshots
  include_tasks: snapshot.yml
  tags: [never, snapshot]