- name: Create a snapshot
  vmware_guest_snapshot:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    datacenter: "{{ datacenter_name }}"
    folder: "/{{ datacenter_name }}/vm/"
    name: "{{ item }}"
    state: present
    snapshot_name: "{{ item }}-snap"
    description: "{{ item }}-snapshot image"
  delegate_to: localhost
  loop: 
    - "dev-rhel8-1"
    - "dev-rhel8-2"
    - "dev-rhel8-3"
  tags: [never, snapshot]